import { MigrationInterface, QueryRunner } from "typeorm";

export class InsertNationalParks1715850000000 implements MigrationInterface {
    name = 'InsertNationalParks1715850000000'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`
            INSERT INTO park ("name", "code", "latitude", "longitude", "description", "state", "region", "imageUrl", "websiteUrl")
            VALUES
            ('Acadia National Park', 'ACAD', 44.3386, -68.2734, 'The first national park east of the Mississippi River, featuring rugged coastline, granite peaks, and diverse wildlife.', 'Maine', 'Northeast', 'https://www.nps.gov/common/uploads/structured_data/3C7B1B8A-1DD8-B71B-0B7EE131C7DFC2F5.jpg', 'https://www.nps.gov/acad/index.htm'),
            ('Arches National Park', 'ARCH', 38.7331, -109.5925, 'Features over 2,000 natural sandstone arches, including the famous Delicate Arch, along with a variety of unique geological formations.', 'Utah', 'Intermountain', 'https://www.nps.gov/common/uploads/structured_data/3C7B1B8A-1DD8-B71B-0B7EE131C7DFC2F5.jpg', 'https://www.nps.gov/arch/index.htm'),
            ('Badlands National Park', 'BADL', 43.8554, -102.3397, 'Features dramatic landscapes of sharply eroded buttes, pinnacles, and spires blended with the largest undisturbed mixed grass prairie in the United States.', 'South Dakota', 'Midwest', 'https://www.nps.gov/common/uploads/structured_data/3C7B1B8A-1DD8-B71B-0B7EE131C7DFC2F5.jpg', 'https://www.nps.gov/badl/index.htm'),
            ('Big Bend National Park', 'BIBE', 29.1275, -103.2425, 'Features dramatic canyons, vast desert expanses, and the Rio Grande River, creating a stunning landscape in the Chihuahuan Desert.', 'Texas', 'Intermountain', 'https://www.nps.gov/common/uploads/structured_data/3C7B1B8A-1DD8-B71B-0B7EE131C7DFC2F5.jpg', 'https://www.nps.gov/bibe/index.htm'),
            ('Biscayne National Park', 'BISC', 25.4825, -80.2092, 'Protects a rare combination of aquamarine waters, emerald islands, and fish-bejeweled coral reefs.', 'Florida', 'Southeast', 'https://www.nps.gov/common/uploads/structured_data/3C7B1B8A-1DD8-B71B-0B7EE131C7DFC2F5.jpg', 'https://www.nps.gov/bisc/index.htm'),
            ('Black Canyon of the Gunnison National Park', 'BLCA', 38.5778, -107.7278, 'Features some of the steepest cliffs, oldest rock, and craggiest spires in North America.', 'Colorado', 'Intermountain', 'https://www.nps.gov/common/uploads/structured_data/3C7B1B8A-1DD8-B71B-0B7EE131C7DFC2F5.jpg', 'https://www.nps.gov/blca/index.htm'),
            ('Bryce Canyon National Park', 'BRCA', 37.5933, -112.1872, 'Features a series of horseshoe-shaped amphitheaters carved from the eastern edge of the Paunsaugunt Plateau.', 'Utah', 'Intermountain', 'https://www.nps.gov/common/uploads/structured_data/3C7B1B8A-1DD8-B71B-0B7EE131C7DFC2F5.jpg', 'https://www.nps.gov/brca/index.htm'),
            ('Canyonlands National Park', 'CANY', 38.3269, -109.8783, 'Features a colorful landscape of canyons, mesas, and buttes carved by the Colorado River and its tributaries.', 'Utah', 'Intermountain', 'https://www.nps.gov/common/uploads/structured_data/3C7B1B8A-1DD8-B71B-0B7EE131C7DFC2F5.jpg', 'https://www.nps.gov/cany/index.htm'),
            ('Capitol Reef National Park', 'CARE', 38.2833, -111.2500, 'Features the Waterpocket Fold, a 100-mile long wrinkle in the earth''s crust.', 'Utah', 'Intermountain', 'https://www.nps.gov/common/uploads/structured_data/3C7B1B8A-1DD8-B71B-0B7EE131C7DFC2F5.jpg', 'https://www.nps.gov/care/index.htm'),
            ('Carlsbad Caverns National Park', 'CAVE', 32.1753, -104.4439, 'Features more than 119 caves formed when sulfuric acid dissolved the surrounding limestone.', 'New Mexico', 'Intermountain', 'https://www.nps.gov/common/uploads/structured_data/3C7B1B8A-1DD8-B71B-0B7EE131C7DFC2F5.jpg', 'https://www.nps.gov/cave/index.htm'),
            ('Channel Islands National Park', 'CHIS', 34.0050, -119.4178, 'Features five remarkable islands and their ocean environment, preserving a wealth of natural and cultural resources.', 'California', 'Pacific West', 'https://www.nps.gov/common/uploads/structured_data/3C7B1B8A-1DD8-B71B-0B7EE131C7DFC2F5.jpg', 'https://www.nps.gov/chis/index.htm'),
            ('Congaree National Park', 'CONG', 33.7828, -80.7828, 'Features the largest intact expanse of old growth bottomland hardwood forest remaining in the southeastern United States.', 'South Carolina', 'Southeast', 'https://www.nps.gov/common/uploads/structured_data/3C7B1B8A-1DD8-B71B-0B7EE131C7DFC2F5.jpg', 'https://www.nps.gov/cong/index.htm'),
            ('Crater Lake National Park', 'CRLA', 42.9446, -122.1090, 'Features the deepest lake in the United States, formed by the collapse of a volcano.', 'Oregon', 'Pacific West', 'https://www.nps.gov/common/uploads/structured_data/3C7B1B8A-1DD8-B71B-0B7EE131C7DFC2F5.jpg', 'https://www.nps.gov/crla/index.htm'),
            ('Cuyahoga Valley National Park', 'CUVA', 41.2417, -81.5500, 'Features a landscape of rolling hills, forests, and farmlands along the Cuyahoga River.', 'Ohio', 'Midwest', 'https://www.nps.gov/common/uploads/structured_data/3C7B1B8A-1DD8-B71B-0B7EE131C7DFC2F5.jpg', 'https://www.nps.gov/cuva/index.htm'),
            ('Death Valley National Park', 'DEVA', 36.5053, -117.0794, 'Features the lowest, hottest, and driest place in North America.', 'California', 'Pacific West', 'https://www.nps.gov/common/uploads/structured_data/3C7B1B8A-1DD8-B71B-0B7EE131C7DFC2F5.jpg', 'https://www.nps.gov/deva/index.htm'),
            ('Denali National Park', 'DENA', 63.1148, -151.1926, 'Features North America''s highest peak, Mount Denali, and vast wilderness areas.', 'Alaska', 'Alaska', 'https://www.nps.gov/common/uploads/structured_data/3C7B1B8A-1DD8-B71B-0B7EE131C7DFC2F5.jpg', 'https://www.nps.gov/dena/index.htm'),
            ('Dry Tortugas National Park', 'DRTO', 24.6286, -82.8733, 'Features seven small islands and the historic Fort Jefferson, accessible only by boat or seaplane.', 'Florida', 'Southeast', 'https://www.nps.gov/common/uploads/structured_data/3C7B1B8A-1DD8-B71B-0B7EE131C7DFC2F5.jpg', 'https://www.nps.gov/drto/index.htm'),
            ('Everglades National Park', 'EVER', 25.2867, -80.9000, 'Features the largest subtropical wilderness in the United States, protecting an unparalleled landscape.', 'Florida', 'Southeast', 'https://www.nps.gov/common/uploads/structured_data/3C7B1B8A-1DD8-B71B-0B7EE131C7DFC2F5.jpg', 'https://www.nps.gov/ever/index.htm'),
            ('Gates of the Arctic National Park', 'GAAR', 67.7833, -153.3000, 'Features pristine wilderness in the Arctic Circle, with no roads or trails.', 'Alaska', 'Alaska', 'https://www.nps.gov/common/uploads/structured_data/3C7B1B8A-1DD8-B71B-0B7EE131C7DFC2F5.jpg', 'https://www.nps.gov/gaar/index.htm'),
            ('Gateway Arch National Park', 'JEFF', 38.6247, -90.1847, 'Features the Gateway Arch, a 630-foot monument to westward expansion.', 'Missouri', 'Midwest', 'https://www.nps.gov/common/uploads/structured_data/3C7B1B8A-1DD8-B71B-0B7EE131C7DFC2F5.jpg', 'https://www.nps.gov/jeff/index.htm'),
            ('Glacier National Park', 'GLAC', 48.7596, -113.7870, 'Features over 700 miles of trails, pristine forests, and spectacular alpine scenery.', 'Montana', 'Intermountain', 'https://www.nps.gov/common/uploads/structured_data/3C7B1B8A-1DD8-B71B-0B7EE131C7DFC2F5.jpg', 'https://www.nps.gov/glac/index.htm'),
            ('Glacier Bay National Park', 'GLBA', 58.5000, -137.0000, 'Features a dynamic landscape of tidewater glaciers, snow-capped mountains, and deep fjords.', 'Alaska', 'Alaska', 'https://www.nps.gov/common/uploads/structured_data/3C7B1B8A-1DD8-B71B-0B7EE131C7DFC2F5.jpg', 'https://www.nps.gov/glba/index.htm'),
            ('Grand Canyon National Park', 'GRCA', 36.0544, -112.1401, 'Features one of the most spectacular examples of erosion anywhere in the world.', 'Arizona', 'Intermountain', 'https://www.nps.gov/common/uploads/structured_data/3C7B1B8A-1DD8-B71B-0B7EE131C7DFC2F5.jpg', 'https://www.nps.gov/grca/index.htm'),
            ('Grand Teton National Park', 'GRTE', 43.7904, -110.6818, 'Features the youngest mountain range in the Rocky Mountains, with dramatic peaks and pristine lakes.', 'Wyoming', 'Intermountain', 'https://www.nps.gov/common/uploads/structured_data/3C7B1B8A-1DD8-B71B-0B7EE131C7DFC2F5.jpg', 'https://www.nps.gov/grte/index.htm'),
            ('Great Basin National Park', 'GRBA', 38.9833, -114.3000, 'Features ancient bristlecone pines, a glacier, and the Lehman Caves.', 'Nevada', 'Intermountain', 'https://www.nps.gov/common/uploads/structured_data/3C7B1B8A-1DD8-B71B-0B7EE131C7DFC2F5.jpg', 'https://www.nps.gov/grba/index.htm'),
            ('Great Sand Dunes National Park', 'GRSA', 37.7918, -105.5122, 'Features the tallest dunes in North America, rising 750 feet from the valley floor.', 'Colorado', 'Intermountain', 'https://www.nps.gov/common/uploads/structured_data/3C7B1B8A-1DD8-B71B-0B7EE131C7DFC2F5.jpg', 'https://www.nps.gov/grsa/index.htm'),
            ('Great Smoky Mountains National Park', 'GRSM', 35.6117, -83.4894, 'Features ancient mountains, diverse plant and animal life, and the beauty of the southern Appalachian culture.', 'Tennessee', 'Southeast', 'https://www.nps.gov/common/uploads/structured_data/3C7B1B8A-1DD8-B71B-0B7EE131C7DFC2F5.jpg', 'https://www.nps.gov/grsm/index.htm'),
            ('Guadalupe Mountains National Park', 'GUMO', 31.9450, -104.8733, 'Features the four highest peaks in Texas and an extensive fossil reef.', 'Texas', 'Intermountain', 'https://www.nps.gov/common/uploads/structured_data/3C7B1B8A-1DD8-B71B-0B7EE131C7DFC2F5.jpg', 'https://www.nps.gov/gumo/index.htm'),
            ('Haleakalā National Park', 'HALE', 20.7206, -156.1553, 'Features the world''s largest dormant volcano and a unique ecosystem.', 'Hawaii', 'Pacific West', 'https://www.nps.gov/common/uploads/structured_data/3C7B1B8A-1DD8-B71B-0B7EE131C7DFC2F5.jpg', 'https://www.nps.gov/hale/index.htm'),
            ('Hawai''i Volcanoes National Park', 'HAVO', 19.3833, -155.2000, 'Features two of the world''s most active volcanoes and unique volcanic landscapes.', 'Hawaii', 'Pacific West', 'https://www.nps.gov/common/uploads/structured_data/3C7B1B8A-1DD8-B71B-0B7EE131C7DFC2F5.jpg', 'https://www.nps.gov/havo/index.htm'),
            ('Hot Springs National Park', 'HOSP', 34.5139, -93.0542, 'Features 47 natural hot springs and historic bathhouses.', 'Arkansas', 'Southeast', 'https://www.nps.gov/common/uploads/structured_data/3C7B1B8A-1DD8-B71B-0B7EE131C7DFC2F5.jpg', 'https://www.nps.gov/hosp/index.htm'),
            ('Indiana Dunes National Park', 'INDU', 41.6533, -87.0525, 'Features 15 miles of the southern shore of Lake Michigan and 15,000 acres of beach, woods, marshes, and prairie.', 'Indiana', 'Midwest', 'https://www.nps.gov/common/uploads/structured_data/3C7B1B8A-1DD8-B71B-0B7EE131C7DFC2F5.jpg', 'https://www.nps.gov/indu/index.htm'),
            ('Isle Royale National Park', 'ISRO', 48.1000, -88.5500, 'Features a remote island wilderness in Lake Superior, accessible only by boat or seaplane.', 'Michigan', 'Midwest', 'https://www.nps.gov/common/uploads/structured_data/3C7B1B8A-1DD8-B71B-0B7EE131C7DFC2F5.jpg', 'https://www.nps.gov/isro/index.htm'),
            ('Joshua Tree National Park', 'JOTR', 33.8734, -115.9010, 'Features two distinct desert ecosystems and the iconic Joshua trees.', 'California', 'Pacific West', 'https://www.nps.gov/common/uploads/structured_data/3C7B1B8A-1DD8-B71B-0B7EE131C7DFC2F5.jpg', 'https://www.nps.gov/jotr/index.htm'),
            ('Katmai National Park', 'KATM', 58.5000, -155.0000, 'Features the Valley of Ten Thousand Smokes and the world''s largest protected population of brown bears.', 'Alaska', 'Alaska', 'https://www.nps.gov/common/uploads/structured_data/3C7B1B8A-1DD8-B71B-0B7EE131C7DFC2F5.jpg', 'https://www.nps.gov/katm/index.htm'),
            ('Kenai Fjords National Park', 'KEFJ', 59.9167, -149.6500, 'Features glaciers, fjords, and abundant marine wildlife.', 'Alaska', 'Alaska', 'https://www.nps.gov/common/uploads/structured_data/3C7B1B8A-1DD8-B71B-0B7EE131C7DFC2F5.jpg', 'https://www.nps.gov/kefj/index.htm'),
            ('Kings Canyon National Park', 'KICA', 36.8000, -118.5500, 'Features dramatic mountain scenery and the deepest canyon in the United States.', 'California', 'Pacific West', 'https://www.nps.gov/common/uploads/structured_data/3C7B1B8A-1DD8-B71B-0B7EE131C7DFC2F5.jpg', 'https://www.nps.gov/kica/index.htm'),
            ('Kobuk Valley National Park', 'KOVA', 67.5500, -159.2833, 'Features the Great Kobuk Sand Dunes and the annual caribou migration.', 'Alaska', 'Alaska', 'https://www.nps.gov/common/uploads/structured_data/3C7B1B8A-1DD8-B71B-0B7EE131C7DFC2F5.jpg', 'https://www.nps.gov/kova/index.htm'),
            ('Lake Clark National Park', 'LACL', 60.9667, -153.4167, 'Features a remote wilderness with active volcanoes, glaciers, and abundant wildlife.', 'Alaska', 'Alaska', 'https://www.nps.gov/common/uploads/structured_data/3C7B1B8A-1DD8-B71B-0B7EE131C7DFC2F5.jpg', 'https://www.nps.gov/lacl/index.htm'),
            ('Lassen Volcanic National Park', 'LAVO', 40.4978, -121.4206, 'Features all four types of volcanoes found in the world.', 'California', 'Pacific West', 'https://www.nps.gov/common/uploads/structured_data/3C7B1B8A-1DD8-B71B-0B7EE131C7DFC2F5.jpg', 'https://www.nps.gov/lavo/index.htm'),
            ('Mammoth Cave National Park', 'MACA', 37.1864, -86.1003, 'Features the world''s longest known cave system.', 'Kentucky', 'Southeast', 'https://www.nps.gov/common/uploads/structured_data/3C7B1B8A-1DD8-B71B-0B7EE131C7DFC2F5.jpg', 'https://www.nps.gov/maca/index.htm'),
            ('Mesa Verde National Park', 'MEVE', 37.2308, -108.4617, 'Features well-preserved Ancestral Puebloan cliff dwellings.', 'Colorado', 'Intermountain', 'https://www.nps.gov/common/uploads/structured_data/3C7B1B8A-1DD8-B71B-0B7EE131C7DFC2F5.jpg', 'https://www.nps.gov/meve/index.htm'),
            ('Mount Rainier National Park', 'MORA', 46.8523, -121.7603, 'Features an active volcano and the most glaciated peak in the contiguous United States.', 'Washington', 'Pacific West', 'https://www.nps.gov/common/uploads/structured_data/3C7B1B8A-1DD8-B71B-0B7EE131C7DFC2F5.jpg', 'https://www.nps.gov/mora/index.htm'),
            ('New River Gorge National Park', 'NERI', 38.0667, -81.0833, 'Features one of the oldest rivers in the world and dramatic gorge scenery.', 'West Virginia', 'Northeast', 'https://www.nps.gov/common/uploads/structured_data/3C7B1B8A-1DD8-B71B-0B7EE131C7DFC2F5.jpg', 'https://www.nps.gov/neri/index.htm'),
            ('North Cascades National Park', 'NOCA', 48.7000, -121.2000, 'Features jagged peaks, deep valleys, and over 300 glaciers.', 'Washington', 'Pacific West', 'https://www.nps.gov/common/uploads/structured_data/3C7B1B8A-1DD8-B71B-0B7EE131C7DFC2F5.jpg', 'https://www.nps.gov/noca/index.htm'),
            ('Olympic National Park', 'OLYM', 47.8021, -123.6044, 'Features three distinct ecosystems: subalpine forest, temperate rainforest, and wild coastline.', 'Washington', 'Pacific West', 'https://www.nps.gov/common/uploads/structured_data/3C7B1B8A-1DD8-B71B-0B7EE131C7DFC2F5.jpg', 'https://www.nps.gov/olym/index.htm'),
            ('Petrified Forest National Park', 'PEFO', 35.0667, -109.7833, 'Features one of the world''s largest and most colorful concentrations of petrified wood.', 'Arizona', 'Intermountain', 'https://www.nps.gov/common/uploads/structured_data/3C7B1B8A-1DD8-B71B-0B7EE131C7DFC2F5.jpg', 'https://www.nps.gov/pefo/index.htm'),
            ('Pinnacles National Park', 'PINN', 36.4914, -121.1833, 'Features unique rock formations and talus caves.', 'California', 'Pacific West', 'https://www.nps.gov/common/uploads/structured_data/3C7B1B8A-1DD8-B71B-0B7EE131C7DFC2F5.jpg', 'https://www.nps.gov/pinn/index.htm'),
            ('Redwood National Park', 'REDW', 41.2131, -124.0046, 'Features the world''s tallest trees and old-growth coastal redwood forests.', 'California', 'Pacific West', 'https://www.nps.gov/common/uploads/structured_data/3C7B1B8A-1DD8-B71B-0B7EE131C7DFC2F5.jpg', 'https://www.nps.gov/redw/index.htm'),
            ('Rocky Mountain National Park', 'ROMO', 40.3428, -105.6836, 'Features spectacular mountain scenery and diverse wildlife.', 'Colorado', 'Intermountain', 'https://www.nps.gov/common/uploads/structured_data/3C7B1B8A-1DD8-B71B-0B7EE131C7DFC2F5.jpg', 'https://www.nps.gov/romo/index.htm'),
            ('Saguaro National Park', 'SAGU', 32.1667, -110.7333, 'Features the nation''s largest cacti and unique Sonoran Desert ecosystem.', 'Arizona', 'Intermountain', 'https://www.nps.gov/common/uploads/structured_data/3C7B1B8A-1DD8-B71B-0B7EE131C7DFC2F5.jpg', 'https://www.nps.gov/sagu/index.htm'),
            ('Sequoia National Park', 'SEKI', 36.4864, -118.5658, 'Features the world''s largest trees and dramatic mountain scenery.', 'California', 'Pacific West', 'https://www.nps.gov/common/uploads/structured_data/3C7B1B8A-1DD8-B71B-0B7EE131C7DFC2F5.jpg', 'https://www.nps.gov/seki/index.htm'),
            ('Shenandoah National Park', 'SHEN', 38.5333, -78.3500, 'Features the scenic Skyline Drive and the Blue Ridge Mountains.', 'Virginia', 'Northeast', 'https://www.nps.gov/common/uploads/structured_data/3C7B1B8A-1DD8-B71B-0B7EE131C7DFC2F5.jpg', 'https://www.nps.gov/shen/index.htm'),
            ('Theodore Roosevelt National Park', 'THRO', 46.9667, -103.4500, 'Features badlands, wildlife, and the legacy of President Theodore Roosevelt.', 'North Dakota', 'Midwest', 'https://www.nps.gov/common/uploads/structured_data/3C7B1B8A-1DD8-B71B-0B7EE131C7DFC2F5.jpg', 'https://www.nps.gov/thro/index.htm'),
            ('Virgin Islands National Park', 'VIIS', 18.3333, -64.7333, 'Features pristine beaches, coral reefs, and historic sugar plantation ruins.', 'U.S. Virgin Islands', 'Southeast', 'https://www.nps.gov/common/uploads/structured_data/3C7B1B8A-1DD8-B71B-0B7EE131C7DFC2F5.jpg', 'https://www.nps.gov/viis/index.htm'),
            ('Voyageurs National Park', 'VOYA', 48.5000, -92.8833, 'Features interconnected waterways and pristine forests.', 'Minnesota', 'Midwest', 'https://www.nps.gov/common/uploads/structured_data/3C7B1B8A-1DD8-B71B-0B7EE131C7DFC2F5.jpg', 'https://www.nps.gov/voya/index.htm'),
            ('White Sands National Park', 'WHSA', 32.7797, -106.1717, 'Features the world''s largest gypsum dunefield.', 'New Mexico', 'Intermountain', 'https://www.nps.gov/common/uploads/structured_data/3C7B1B8A-1DD8-B71B-0B7EE131C7DFC2F5.jpg', 'https://www.nps.gov/whsa/index.htm'),
            ('Wind Cave National Park', 'WICA', 43.5583, -103.4783, 'Features one of the world''s longest and most complex caves.', 'South Dakota', 'Midwest', 'https://www.nps.gov/common/uploads/structured_data/3C7B1B8A-1DD8-B71B-0B7EE131C7DFC2F5.jpg', 'https://www.nps.gov/wica/index.htm'),
            ('Wrangell-St. Elias National Park', 'WRST', 61.0000, -142.0000, 'Features the largest national park in the United States and the continent''s largest collection of glaciers.', 'Alaska', 'Alaska', 'https://www.nps.gov/common/uploads/structured_data/3C7B1B8A-1DD8-B71B-0B7EE131C7DFC2F5.jpg', 'https://www.nps.gov/wrst/index.htm'),
            ('Yellowstone National Park', 'YELL', 44.4280, -110.5885, 'Features the world''s largest concentration of geysers and hot springs.', 'Wyoming', 'Intermountain', 'https://www.nps.gov/common/uploads/structured_data/3C7B1B8A-1DD8-B71B-0B7EE131C7DFC2F5.jpg', 'https://www.nps.gov/yell/index.htm'),
            ('Yosemite National Park', 'YOSE', 37.8651, -119.5383, 'Features dramatic granite cliffs, waterfalls, and giant sequoia groves.', 'California', 'Pacific West', 'https://www.nps.gov/common/uploads/structured_data/3C7B1B8A-1DD8-B71B-0B7EE131C7DFC2F5.jpg', 'https://www.nps.gov/yose/index.htm'),
            ('Zion National Park', 'ZION', 37.2982, -112.9822, 'Features dramatic canyons, towering cliffs, and the Virgin River, creating a stunning landscape of red rock formations.', 'Utah', 'Intermountain', 'https://www.nps.gov/common/uploads/structured_data/3C7B1B8A-1DD8-B71B-0B7EE131C7DFC2F5.jpg', 'https://www.nps.gov/zion/index.htm');
        `);

        // Create indexes
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS idx_park_name ON park ("name");`);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS idx_park_code ON park ("code");`);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS idx_park_state ON park ("state");`);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS idx_park_region ON park ("region");`);
        await queryRunner.query(`CREATE INDEX IF NOT EXISTS idx_park_coordinates ON park ("latitude", "longitude");`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        // Remove indexes
        await queryRunner.query(`DROP INDEX IF EXISTS idx_park_name;`);
        await queryRunner.query(`DROP INDEX IF EXISTS idx_park_code;`);
        await queryRunner.query(`DROP INDEX IF EXISTS idx_park_state;`);
        await queryRunner.query(`DROP INDEX IF EXISTS idx_park_region;`);
        await queryRunner.query(`DROP INDEX IF EXISTS idx_park_coordinates;`);

        // Remove all parks
        await queryRunner.query(`DELETE FROM park;`);
    }
} 